github: gnh1201
open_collective: welsonjs
liberapay: catswords
patreon: catswords
ko_fi: catswords
custom: ['https://www.buymeacoffee.com/catswords', 'https://m.expert.naver.com/mobile/expert/product/detail?storeId=100051156&productId=100144540']
